changelog:
  categories:
    - title: "Novidades"
      labels:
        - "feature"
        - "enhancement"
    - title: "Correções"
      labels:
        - "fix"
        - "bug"
    - title: "Build & CI"
      labels:
        - "build"
        - "ci"
        - "infra"
    - title: "Outras mudanças"
      labels:
        - "*"
